var anObject = new Object();
console.log('anObject value :  ', anObject);
console.log('typeof anObject value :  ', typeof anObject);
var anArray = new Array();
console.log('anArray value :  ', anArray);
console.log('typeof anArray value :  ', typeof anArray);
var aFunction = new Function();
console.log('aFunction value :  ', aFunction);
console.log('typeof aFunction value :  ', typeof aFunction);
var aString = new String();
console.log('aString value :  ', aString);
console.log('typeof aString value :  ', typeof aString);
var aNumber = new Number();
console.log('aNumber value :  ', aNumber);
console.log('typeof aNumber value :  ', typeof aNumber);
var aBoolean = new Boolean();
console.log('aBoolean value :  ', aBoolean);
console.log('typeof aBoolean value :  ', typeof aBoolean);
